export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILED = 'AUTH_FAILED'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const CREATE_AGENDA = 'CREATE_AGENDA'
export const CREATE_AGENDA_SUCCESS = 'CREATE_AGENDA_SUCCESS'




